Get-ChildItem -Path binaries\*.*    -Filter *.exe      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path binaries\*.*    -Filter *.dbg      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path lac\*.*         -Filter *.txt      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path lib\*.*         -Filter *.compiled -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path lib\*.*         -Filter *.o        -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path lib\*.*         -Filter *.obj      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path lib\*.*         -Filter *.ppu      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path lib\*.*         -Filter *.res      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path opcodes\lib\*.* -Filter *.compiled -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path opcodes\lib\*.* -Filter *.o        -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path opcodes\lib\*.* -Filter *.obj      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path opcodes\lib\*.* -Filter *.ppu      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path opcodes\lib\*.* -Filter *.res      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path test_files\*.*  -Filter *.log      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path test_prog\*.*   -Filter *.compiled -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path test_prog\*.*   -Filter *.dbg      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path test_prog\*.*   -Filter *.exe      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path test_prog\*.*   -Filter *.log      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path test_prog\*.*   -Filter *.o        -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path test_prog\*.*   -Filter *.obj      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path test_prog\*.*   -Filter *.ppu      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path test_prog\*.*   -Filter *.res      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path test_prog\*.*   -Filter *.txt      -Recurse | ForEach-Object {$_.Delete()}
Get-ChildItem -Path test_prog -Recurse -Directory -Name | Where-Object { $_ -like "*lib" } | ForEach-Object { Remove-Item "test_prog\$_" -Recurse }